version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      # Types ['Bukkit/Spigot', 'Quilt', 'Fabric', 'Forge'] DELETE LINE FOR VANNILA
      TYPE: FABRIC
      MEMORY: 2G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft_data:/data

