version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "Serverr00t"
    MYSQL_ROOT_PASSWORD: "Serverr00t"
  panel:
    &panel-environment
    # This URL should be the URL that your reverse proxy routes to the panel server
    APP_URL: "https://gamepanel.frigon-e.ca"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "America/Vancouver"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    TRUSTED_PROXIES: "*" # Set this to your proxy IP
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mysql:8.0
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/home/smurfssmur/pterodactyl/panel/data/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    networks:
      - local
      - web
    links:
      - database
      - cache
    volumes:
      - "/home/smurfssmur/pterodactyl/panel/data/var/:/app/var/"
      - "/home/smurfssmur/pterodactyl/panel/data/nginx/:/etc/nginx/http.d/"
      - "/home/smurfssmur/pterodactyl/panel/data/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.pterodactyl_panel.entrypoints=http"
      - "traefik.http.routers.pterodactyl_panel.rule=Host(`gamepanel.frigon-e.ca`)"
      - "traefik.http.middlewares.pterodactyl_panel-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pterodactyl_panel.middlewares=pterodactyl_panel-https-redirect"
      # HTTPS
      - "traefik.http.routers.pterodactyl_panel-secure.entrypoints=https"
      - "traefik.http.routers.pterodactyl_panel-secure.rule=Host(`gamepanel.frigon-e.ca`)"
      - "traefik.http.routers.pterodactyl_panel-secure.tls=true"
      - "traefik.http.routers.pterodactyl_panel-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.pterodactyl_panel-secure.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  local:
    external: false
  web:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
